### ISSUE TITLE
Validation Errors 

### ISSUE THREAD

**Issue by cataluna84** [actions-on-google/dialogflow-conversation-components-nodejs#1]
When clicking on lists or carousels on Actions on Google simulator,  there is a following validation error - 

Error Type
MalformedResponse
expected_inputs[0].possible_intents[0]: intent 'actions.intent.OPTION' is only supported for version 2 and above.

Here is the Response JSON
`{
    "response": "my test app isn’t responding right now. Try again soon.\n",
    "audioResponse": "//NExAASW...",
    "debugInfo": {
        "sharedDebugInfo": [
            {
                "name": "ExecutionResponse",
                "debugInfo": "HarpoonRe..."
            },
            {
                "name": "ResponseValidation",
                "subDebugEntry": [
                    {
                        "name": "MalformedResponse",
                        "debugInfo": "expected_inputs[0].possible_intents[0]: intent 'actions.intent.OPTION' is only supported for version 2 and above."
                    }
                ]
            }
        ]
    },
    "visualResponse": {}
}`

How to resolve this?

**Comment by smishra2** [comment]
Hi @mayankbhaskar007, sorry about that. Can you edit your Action Package to have `"fulfillmentApiVersion": 2` in the conversation object? It should look like this

```
{
 "actions": [
   {
     "description": "Launch intent",
     "name": "MAIN",
     "fulfillment": {
       "conversationName": "mainConversation"
     },
     "intent": {
       "name": "actions.intent.MAIN"
     }
   }
 ],
 "conversations": {
   "mainConversation": {
     "name": "mainConversation",
     "url": "YOUR_HTTP_URL",
     "fulfillmentApiVersion": 2
   }
 }
```

We will update the sample to use this field shortly. Note that you don't need to do any of this if you're using API.AI and that is the path we recommend as easiest for building Assistant apps.

**Comment by cataluna84** [comment]
Thanks for the input. Basically, I am using API.AI and a custom webhook on a local Node.js server and had the above validation issue. The above `"conversations"` key is not in the api.ai/package.json file. So, couldn't insert the `"fulfillmentApiVersion": 2` in the code.

**Comment by acucciniello** [comment]
is there a way around this for Dialogflow?

**Comment by acucciniello** [comment]
I attempted to work around this by using the guide on helpers here:
https://developers.google.com/actions/assistant/helpers#list_and_carousel_option

This still caused the same problem, any ideas on how to get around this?

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
