### ISSUE TITLE
Where is the code for firebase when using google actions sdk

### ISSUE THREAD

**Issue by sarojk562** [actions-on-google/dialogflow-conversation-components-nodejs#10]
I am trying to deploy and test this application but i couldn't find the code for firebase function that needs to be deployed anywhere. Can someone help me with this.?

**Comment by Fleker** [comment]
Depending on whether you're using [Dialogflow](https://github.com/actions-on-google/conversation-components-nodejs/tree/master/dialogflow/functions) or [Actions SDK](https://github.com/actions-on-google/conversation-components-nodejs/tree/master/actions-sdk/functions), you can look in the `functions` directory under each service.
