### ISSUE TITLE
Upgrade API AI version

### ISSUE THREAD

**Issue by Sangdol** [actions-on-google/dialogflow-conversation-components-nodejs#4]
Thanks for the good examples.

I had to spend some hours to figure out why this doesn't work well with the simulator, and [found that I had to upgrade the conversation protocol version](https://developers.google.com/actions/reference/v1/migration).

It would be nicer if the API AI sample file is already upgraded to the newer version.

**Comment by maaaaaaaax** [comment]
Due to inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
