### ISSUE TITLE
Add Device Screenshots of Components

### ISSUE THREAD

**Issue by zzeleznick** [actions-on-google/dialogflow-conversation-components-nodejs#6]
Would it be possible to show the List component looks like on a small device (e.g. iPhone 5c) vs a large device (e.g. Google Pixel XL)?

It's a little disappointing that these visual components don't have any screenshots here.

**Comment by findzaatar** [comment]
You can visit the responses [documentation](https://developers.google.com/actions/assistant/responses#list) to preview the various surfaces available.
