### ISSUE TITLE
Sample seems to be broken

### ISSUE THREAD

**Issue by zzeleznick** [actions-on-google/dialogflow-conversation-components-nodejs#7]
### Steps to Reproduce
1. Restore Agent from zip (`dialogflow/agent.zip`)
2. Click on Google Assistant from Integrations Menu
3. Launch the test app and select `List` from the suggestions

### Fulfillment URL: 
`https://us-central1-conversation-component-sample.cloudfunctions.net/conversationComponentApiAi`

### Change-Id:
`Ibb8e918b355c19a278829af6b102f490b639d1c9`

### Error Response
```
"sharedDebugInfo": [
    {
      "name": "ResponseValidation",
      "subDebugEntry": [
        {
          "debugInfo": "expected_inputs[0].possible_intents[0]: intent 'actions.intent.OPTION' is only supported for version 2 and above.",
          "name": "MalformedResponse"
        }
      ]
    }
  ]
```

**Comment by zzeleznick** [comment]
Seems to be very similar to #1.

Attempted to follow #4 by selecting "Use Actions on Google Conversation API V2", but now I am greeted with `expected_inputs[0].input_prompt.rich_initial_prompt: the first element must be a 'simple_response' or a 'structured_response'.` on launch

**Comment by arnabsen** [comment]
I can reproduce @zzeleznick 's reported behaviour.

**Comment by arnabsen** [comment]
A simple response or structured response is mandatory, so it's not possible to just have a standalone media response

**Comment by sherazlodhi** [comment]
@arnabsen  How to set final_response. I keep getting final_response must be set?

**Comment by arnabsen** [comment]
@sherazlodhi that could be for a number of reasons. you would have to check your cloud function logs to see what exactly is throwing the error.

**Comment by lucaswadedavis** [comment]
@zzeleznick are you still having the same problem, or were you able to resolve it?

**Comment by bartdk-be** [comment]
@lucaswadedavis : I'm having similar issues as well.
`expected_inputs[0].input_prompt.rich_initial_prompt: the first element must be a 'simple_response', a 'structured_response' or a 'custom_response'.`

**Comment by okjuan** [comment]
While testing my Dialogflow agent on the Actions on Google console (`console.actions.google.com`), I got `expected_inputs[0].input_prompt.rich_initial_prompt: the first element must be a 'simple_response' or a 'structured_response'` as well -- the fulfillment logic for the matched intention looked like:

```node
app.intent('My Intention', (conv, {artist}) => {
    conv.ask(new BasicCard({
      text: `This is a basic card.  Text in a basic card can include "quotes" and
      most other unicode characters including emoji 📱.  Basic cards also support
      some markdown formatting like *emphasis* or _italics_, **strong** or
      __bold__, and ***bold itallic*** or ___strong emphasis___ as well as other
      things like line  \nbreaks`, // Note the two spaces before '\n' required for
                                   // a line break to be rendered in the card.
      subtitle: 'This is a subtitle',
      title: 'Title: this is a title',
      display: 'CROPPED',
    }))
})
```

I was able to fix it just by adding a `SimpleResponse` before the `BasicCard` response. Both surfaced in the Actions on Google console (note: the card appeared under the `DISPLAY` tab).

```node
app.intent('My Intention', (conv, {artist}) => {
    conv.ask(new SimpleResponse({
        speech: "Hey, this is a simple response, okay?",
        text: "Hey, this is a simple response, okay?",
    }))
    conv.ask(new BasicCard({
      text: `This is a basic card.  Text in a basic card can include "quotes" and
      most other unicode characters including emoji 📱.  Basic cards also support
      some markdown formatting like *emphasis* or _italics_, **strong** or
      __bold__, and ***bold itallic*** or ___strong emphasis___ as well as other
      things like line  \nbreaks`, // Note the two spaces before '\n' required for
                                   // a line break to be rendered in the card.
      subtitle: 'This is a subtitle',
      title: 'Title: this is a title',
      display: 'CROPPED',
    }))
})
```

Note that you must import the responses in the Node Actions on Google library that you use:
```node
const { dialogflow, BasicCard, SimpleResponse } = require('actions-on-google')
```

**Comment by lucaswadedavis** [comment]
okjuan what version of the **actions-on-google** client library are you using? (You should be able to check the package.json file)

**Comment by findzaatar** [comment]
The sample has been recently updated -- the client library now requires responses to have simple responses as the error message suggests. 

Directly from this [sample](https://github.com/actions-on-google/dialogflow-conversation-components-nodejs/blob/master/functions/index.js#L108): 

// Basic card
app.intent('basic card', (conv) => {
  if (!conv.hasScreen) {
    conv.ask('Sorry, try this on a screen device or select the ' +
      'phone surface in the simulator.');
    return;
  }
  conv.ask('This is the first simple response for a basic card.');
  conv.ask(new Suggestions(intentSuggestions));
  // Create a basic card
  conv.ask(new BasicCard({
    text: `This is a basic card.  Text in a basic card can include "quotes" and
    most other unicode characters including emoji 📱.  Basic cards also support
    some markdown formatting like *emphasis* or _italics_, **strong** or
    __bold__, and ***bold itallic*** or ___strong emphasis___ as well as other
    things like line  \nbreaks`, // Note the two spaces before '\n' required for
                                 // a line break to be rendered in the card.
    subtitle: 'Build Actions',
    title: 'Google Assistant',
    buttons: new Button({
      title: 'This is a button',
      url: 'https://assistant.google.com/',
    }),
    image: new Image({
      url: IMG_URL_AOG,
      alt: 'Google Assistant logo',
    }),
  }));
  conv.ask(new SimpleResponse({
    speech: 'This is the second simple response.',
    text: 'This is the 2nd simple response.',
  }));
});
