### ISSUE TITLE
Missing array braces on button assignment in card creation line 130

### ISSUE THREAD

**Issue by strttn** [actions-on-google/dialogflow-conversation-components-nodejs#9]

**Comment by Fleker** [comment]
Are you referring to the [Dialogflow function](https://github.com/actions-on-google/conversation-components-nodejs/blob/master/dialogflow/functions/index.js#L130)? Did you run into a syntax error when trying to run it?

**Comment by Canain** [comment]
The code uses the wrapper for [`BasicCard`](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/conversation_response.basiccardoptions.html)

The `buttons` property accepts both an array and a single `Button` for ease of use (because right now only one button is allowed).

**Comment by strttn** [comment]
Yes, I'm referring to the Dialogflow function.

I am setting the buttons property after having already instantiated the BasicCard rather than using it within the "new" function.

E.g.

```
let basicCard = new BasicCard({
    text: cardText
});

basicCard.buttons = [new Button({
    title: linkText,
    url: linkUrl
})];
```
Without the square brackets I was getting a malformed response error on sending back the response.

**Comment by Canain** [comment]
Yeah, the wrappers are intended to be created just from the constructor.

If you assign to it manually, you will bypass the abstractions and just directly manipulate the raw [`GoogleActionsV2UiElementsBasicCard`](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/actionssdk_api_v2.googleactionsv2uielementsbasiccard.html) API which can only have `buttons` as an array.

You'll have to assign it with an array like you mentioned.

But this isn't really an issue with the sample as the samples don't manipulate the raw API directly and just use the [wrappers with the constructor](https://github.com/actions-on-google/conversation-components-nodejs/blob/0c151e597fea7c5c6a8766f10c6e0a6cc14c5b6a/dialogflow/functions/index.js#L130) so it's valid.

```javascript
  conv.ask(new BasicCard({
    text: `This is a basic card.  Text in a basic card can include "quotes" and
    most other unicode characters including emoji 📱.  Basic cards also support
    some markdown formatting like *emphasis* or _italics_, **strong** or
    __bold__, and ***bold itallic*** or ___strong emphasis___ as well as other
    things like line  \nbreaks`, // Note the two spaces before '\n' required for
                                 // a line break to be rendered in the card.
    subtitle: 'This is a subtitle',
    title: 'Title: this is a title',
    buttons: new Button({
      title: 'This is a button',
      url: 'https://assistant.google.com/',
    }),
    image: new Image({
      url: IMG_URL_AOG,
      alt: 'Image alternate text',
    }),
  }));
```
